# Generated by Django 2.1.3 on 2018-11-05 03:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0002_auto_20181104_2055'),
        ('round', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movements',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('player_1_movement', models.CharField(choices=[('ROCK', 'Rock'), ('PAPER', 'Paper'), ('SCISSORS', 'Scissors')], max_length=8)),
                ('player_2_movement', models.CharField(choices=[('ROCK', 'Rock'), ('PAPER', 'Paper'), ('SCISSORS', 'Scissors')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='round.Rounds')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.Players')),
            ],
            options={
                'db_table': 'movements',
            },
        ),
    ]
